"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


# class Solution:
#     def findTheDifference(self, s: str, t: str) -> str:

#         return list(collections.Counter(t) - collections.Counter(s))[0]


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        res = 0
        for i in s + t:
            res ^= ord(i)
        return chr(res)




